# Use a JDK to build and run
FROM openjdk:17-jdk-slim

# Create app directory
WORKDIR /app

# Copy the jar generated by Maven
COPY target/timesheet-devops-1.0.jar app.jar

# Expose the port your Spring Boot app runs on
EXPOSE 8080

# Command to run the app
ENTRYPOINT ["java", "-jar", "app.jar"]
